name: 'Setup project'

inputs:
  use_latest_tag:
    description: 'Controls whether to checkout the latest tag or not. Turned off by default.'
    required: false
    default: false
    type: boolean

runs:
  using: composite
  steps:
    - name: 'Checkout the latest tag'
      if: ${{ inputs.use_latest_tag == 'true' }}
      shell: bash
      run: |
        export GIT_TAG=$(git describe --tags --abbrev=0)
        echo "The latest tag: $GIT_TAG"
        git checkout --quiet "$GIT_TAG"
    ##########
    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - name: 'Setup npm cache'
      uses: actions/cache@v4
      with:
        ket: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        path: ~/.npm
        restore-keys: |
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - name: 'Install npm dependencies'
      run: npm clean-install
