name: Default
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GIT_TAG_NAME: stable

jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - name: Setup pnpm
        run: |
          corepack enable
          corepack install
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Perform code analyzer check
        run: pnpm run lint
      - name: Perform format check
        run: pnpm run style
      - name: Perform tests
        run: pnpm run test
  publish-tag:
    name: Publish tag
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Create tag
        run: git tag --force ${{ env.GIT_TAG_NAME }}
      - name: Push tag
        run: git push --force origin ${{ env.GIT_TAG_NAME }}
