name: Default
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GIT_TAG_NAME: stable

jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install npm dependencies
        run: npm clean-install
      - name: Perform code analyzer and format check
        run: npm run lint
      - name: Perform tests
        run: npm run test
  publish-tag:
    name: Publish tag
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Create tag
        run: git tag --force ${{ env.GIT_TAG_NAME }}
      - name: Push tag
        run: git push --force origin ${{ env.GIT_TAG_NAME }}
