name: Run
on:
  workflow_call:
    inputs:
      source_name:
        description: "Source site name"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      source_name:
        description: "Source site name"
        required: true
        type: choice
        options:
          - 'merriamWebster'
          - 'oxfordLearnersDictionaries'
          - 'theFreeDictionary'

env:
  GIT_TAG_NAME: stable
  LOG_FILE_PATH: debug.log
  LOG_LEVEL: debug
  LOG_PRETTY: true
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
  NODE_ENV: 'production'

jobs:
  run:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_TAG_NAME }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - name: Setup pnpm
        run: |
          corepack enable
          corepack install
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Run application with "${{ inputs.source_name }}" source
        run: pnpm start -- ${{ inputs.source_name }}
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.source_name }} run ${{ env.LOG_LEVEL }} log
          path: ${{ env.LOG_FILE_PATH }}
          retention-days: 7
