name: Run
on:
  workflow_call:
    inputs:
      source_name:
        description: "Source site name"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      source_name:
        description: "Source site name"
        required: true
        type: choice
        options:
          - 'merriamWebster'
          - 'oxfordLearnersDictionaries'
          - 'theFreeDictionary'

env:
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
  NODE_ENV: 'production'

jobs:
  run:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install npm dependencies
        run: npm clean-install
      - name: Run application with "${{ inputs.source_name }}" source
        run: npm start -- ${{ inputs.source_name }}
