name: Run
on:
  workflow_call:
    inputs:
      source_name:
        description: "Name of the source"
        required: true
        type: string
      source_url:
        description: "RSS feed Url for the source"
        required: true
        type: string
      source_item_index:
        description: "Index of the latest item in the returned RSS feed"
        required: true
        type: number
      post_hashtag:
        description: "Hashtag to add to the post"
        default: ""
        type: string

env:
  GIT_TAG_NAME: stable
  LOG_FILE_PATH: debug.log
  LOG_LEVEL: debug
  LOG_PRETTY: true
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
  NODE_ENV: 'production'

  SOURCE_NAME: ${{ inputs.source_name }}
  SOURCE_URL: ${{ inputs.source_url }}
  SOURCE_ITEM_INDEX: ${{ inputs.source_item_index }}
  POST_HASHTAG: ${{ inputs.post_hashtag }}
  POST_LANGUAGE: 'en-GB'
  POST_VISIBILITY: 'public'

jobs:
  run:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_TAG_NAME }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Setup pnpm
        shell: bash
        run: |
          corepack enable
          corepack install
      - name: Get pnpm store directory
        id: pnpm_store
        shell: bash
        run: |
          echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          path: ${{ steps.pnpm_store.outputs.path }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Run application for "${{ env.SOURCE_NAME }}" source
        run: pnpm start
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SOURCE_NAME }} run ${{ env.LOG_LEVEL }} log"
          path: ${{ env.LOG_FILE_PATH }}
          retention-days: 7
