name: Scheduled Run

on:
  schedule:
    - cron: '00 08 * * *'
    # - cron: '00 10 * * *'
    - cron: '00 12 * * *'

jobs:
  set-source-name:
    name: Set source name
    runs-on: ubuntu-latest
    outputs:
      source_name: ${{ steps.output.outputs.source_name }}

    steps:
      - name: Set SOURCE_NAME to "Merriam Webster"
        if: ${{ github.event.schedule == '00 08 * * *' }}
        run: echo "SOURCE_NAME=merriamWebster" >> $GITHUB_ENV

      # - name: Set SOURCE_NAME to "Oxford Learner's Dictionaries"
      # if: ${{ github.event.schedule == '00 10 * * *' }}
      #   run: echo "SOURCE_NAME=oxfordLearnersDictionaries" >> $GITHUB_ENV

      - name: Set SOURCE_NAME to "The Free Dictionary"
        if: ${{ github.event.schedule == '00 12 * * *' }}
        run: echo "SOURCE_NAME=theFreeDictionary" >> $GITHUB_ENV

      - name: Output source name from the job
        id: output
        run: echo "source_name=$SOURCE_NAME" >> $GITHUB_OUTPUT

  trigger-run:
    name: Trigger run workflow
    needs:
      - set-source-name
    uses: ./.github/workflows/run.yml
    with:
      source_name: ${{ needs.set-source-name.outputs.source_name }}
    secrets: inherit
