name: "Source: The Free Dictionary"

on:
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch:

jobs:
  run:
    name: Trigger run workflow
    uses: ./.github/workflows/run.yml
    with:
      source_name: "The Free Dictionary"
      source_url: "https://www.thefreedictionary.com/_/WoD/rss.aspx"
      source_item_index: 0
      source_post_hashtag: "#TheFreeDictionary"
    secrets: inherit
